### ISSUE TITLE
Visits where visitor and user ID are not present

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/buda-events-collector#24]
Hey there! While exploring the RAW visits data on BigQuery I spotted that some visits we were receiving have empty `visitor_id` and `user_id`.

Checking Redshift, seems this is happening too there. For example, [there are 1,893,159 visits between `2019-03-24` and `2019-03-26` that have null or empty `visitor_id` and `user_id`](https://looker.buffer.com/sql/99jwwdxrffgpmn).

The [same query against BigQuery data returns 2,053,177 records](https://looker.buffer.com/sql/gg4nsbnyhzsjg2).

These visits are going the following URIs:
![2019-03-27_10:45:53_1659x656](https://user-images.githubusercontent.com/1682202/55066197-8b513580-507d-11e9-9d81-e2c3d22c2fb7.png)

Most of them seems to be back-end related but there are a few like `https://buffer.com/guides/chrome/installed` that got a few visits without `visitor_id` and `user_id`. 

cc @mallen5311 @djfarrelly @michael-erasmus

**Comment by mallen5311** [comment]
I'd be in favor of not generating any visit record if there isn't one of the visitor_id or user_id available, as visits only have value to us if we can associate them with one of those ids. Not sure if this is an easy change to make in the code where the visit gets created though 😄
