### ISSUE TITLE
Open Source the repo!

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/buda-events-collector#8]
Now that we've cleaned up the folder structure and [improved the README](https://github.com/bufferapp/buffer-events-collector) I think we can move forward and open source this repository. 💃 

The only thing that's in the history that could concern us is the [Lambda Amazon ARN](https://github.com/bufferapp/buffer-events-collector/blob/9af1479f45af5e7618d41183cbec8a1c40614d5b/lambda/functions/buffer-app-events-to-firehose/function.json#L7). Happy to delete the folder from the history if this information is dangerous at any level! 😄   

cc @michael-erasmus and @djfarrelly

**Comment by michael-erasmus** [comment]
Boom! Hurray for OSS :heart:
